# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhaCli < Formula
  desc ""
  homepage ""
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.5/gha-cli-1.0.5-darwin-amd64.tar.gz"
      sha256 "a231e684842470e3d2ae16069c802fe3172585bfe1a57c8c427c2eb64949d41c"

      def install
        bin.install "gha-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.5/gha-cli-1.0.5-darwin-arm64.tar.gz"
      sha256 "bb8f6701acc7c2790c40f7efa7a4185d8b2e5f932f49114a6b64d83daf0dffa6"

      def install
        bin.install "gha-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.5/gha-cli-1.0.5-linux-arm64.tar.gz"
      sha256 "0ad454a26da0188b4053d1005f5944eaefa600901a86f4c413c28e304fb0f7b1"

      def install
        bin.install "gha-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.5/gha-cli-1.0.5-linux-amd64.tar.gz"
      sha256 "46089314f3402435adeaae291dc0df34d28a9192df09bbfe75b2e114a4f6d823"

      def install
        bin.install "gha-cli"
      end
    end
  end
end
