# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhaCli < Formula
  desc ""
  homepage ""
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.2/gha-cli-1.0.2-darwin-arm64.tar.gz"
      sha256 "2a213cce1d321741ec905fe8d2132de2d04f39b74db664105aef7830b51798dc"

      def install
        bin.install "gha-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.2/gha-cli-1.0.2-darwin-amd64.tar.gz"
      sha256 "f9bb05915e55ff54150829146fbdbf7115ea7ddc2961835da8ff6b12f5fabb8c"

      def install
        bin.install "gha-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.2/gha-cli-1.0.2-linux-amd64.tar.gz"
      sha256 "890c4dd4b9af86c309fd892e3e388e64f326959322b7bc00e45bbb4651a46c87"

      def install
        bin.install "gha-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Norsk-Tipping/gha-cli/releases/download/v1.0.2/gha-cli-1.0.2-linux-arm64.tar.gz"
      sha256 "ae65304b47fc54fea1410b8f5ca90a4f13465e574d81b2938e4c162bb87d0b3a"

      def install
        bin.install "gha-cli"
      end
    end
  end
end
