# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metagraf < Formula
  desc ""
  homepage ""
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/metagraf/releases/download/v0.1.8/mg-0.1.8-darwin-amd64.tar.gz"
      sha256 "69cddf9f90ced8cfd688acea2494b76b38eeef47160e87b10dc9f46df6297b3a"

      def install
        bin.install "mg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/metagraf/releases/download/v0.1.8/mg-0.1.8-linux-amd64.tar.gz"
      sha256 "05ab57bdecfe2dca0426a71e9daf95817d60da6934ee988b6bba1e7b232a4be0"

      def install
        bin.install "mg"
      end
    end
  end
end
