# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metagraf < Formula
  desc ""
  homepage ""
  version "0.1.16"

  on_macos do
    url "https://github.com/Norsk-Tipping/metagraf/releases/download/v0.1.16/mg-0.1.16-darwin-amd64.tar.gz"
    sha256 "8f5e3a8efe1a955679b0055ec3b143d4b3a2d51e68ee483c5f4996ca53f5fb34"

    def install
      bin.install "mg"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Metagraf
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Norsk-Tipping/metagraf/releases/download/v0.1.16/mg-0.1.16-linux-amd64.tar.gz"
      sha256 "ce0514db49ecbf1140ae50cb3775ff96aed30c6182d1b5eb9ed127f0d5642ffd"

      def install
        bin.install "mg"
      end
    end
  end
end
