# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ip-lookup" do
  module GitHubHelper
    def self.token
      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise "HOMEBREW_GITHUB_API_TOKEN is not set" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/Norsk-Tipping/los-common-utilities/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.1.9"

  on_macos do
    on_intel do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "4f8f70e645e811b6ecd4ea5c0e3dcf289ce876e06c87db531304c5a199e47a95"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "61c126b8f617a0d6ff89cd952ff83531d26049c41a793593959e5e05b89be62f"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "8ec1c946a0b6377bad2ad174825be196db17923d3f63802acdbca3c7840d3c3a"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "859e1cfd60b105e68386d43a59191dfeda3b645e2fe5034ca3efbdbff934715c"
    end
  end

  name "aws-ip-lookup"
  desc "Look up which AWS service and region owns a given IP address"
  homepage "https://github.com/Norsk-Tipping/los-common-utilities"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip-lookup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-ip-lookup"]
    end
  end

  # No zap stanza required

end
