# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ip-lookup" do
  module GitHubHelper
    def self.token
      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise "HOMEBREW_GITHUB_API_TOKEN is not set" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/Norsk-Tipping/los-common-utilities/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.1.8"

  on_macos do
    on_intel do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "2217c0124f591223ce7c55d687e4b79b045abfa7b00167f5b49e06a1d56e1691"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "eba839e3cab046895d4d37df2b7bb66245af30fac122c05508417532e3487925"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "4e0f4983db98d1254711a309cb9ddeea9acb04414cecef052b934db84b77590f"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("v#{version}", "aws-ip-lookup_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "2e9d01008b6b52444d90318367f1c0c71f4999948500f7011afab258daa41ac6"
    end
  end

  name "aws-ip-lookup"
  desc "Look up which AWS service and region owns a given IP address"
  homepage "https://github.com/Norsk-Tipping/los-common-utilities"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip-lookup"

  # No zap stanza required

end
