# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ip-lookup" do
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/Norsk-Tipping/los-common-utilities/releases/download/v#{version}/aws-ip-lookup_#{version}_darwin_amd64.tar.gz"
      sha256 "1e1383e5ed6a4b84482e1a206a97630c1a9b66c9d8bda020298eec565876ba4c"
    end
    on_arm do
      url "https://github.com/Norsk-Tipping/los-common-utilities/releases/download/v#{version}/aws-ip-lookup_#{version}_darwin_arm64.tar.gz"
      sha256 "6a1aee611444dcf47155fc04ba8dfbc7f57289114ebe8792deff9c86777bfbc3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Norsk-Tipping/los-common-utilities/releases/download/v#{version}/aws-ip-lookup_#{version}_linux_amd64.tar.gz"
      sha256 "141981c3397033616dd28297595df0042ea0faa4bf7f3523a08b3ef7f9aebd96"
    end
    on_arm do
      url "https://github.com/Norsk-Tipping/los-common-utilities/releases/download/v#{version}/aws-ip-lookup_#{version}_linux_arm64.tar.gz"
      sha256 "ea1c3476cda3dadcbc086f237e2f71c5c8b93554154afe5d41c4e0375d7dc061"
    end
  end

  name "aws-ip-lookup"
  desc "Look up which AWS service and region owns a given IP address"
  homepage "https://github.com/Norsk-Tipping/los-common-utilities"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip-lookup"

  # No zap stanza required

end
